ifeq "$(PLATFORM)" ""
PLATFORM := $(shell uname)
endif

ifeq "$(PLATFORM)" "Darwin"
BUILDCOMMAND := "swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib"
else
BUILDCOMMAND := "swift build -Xcc -fblocks -Xlinker -rpath -Xlinker .build/debug"
endif

fetch:
	swift build --fetch
	find Packages/ -type d -name Tests | xargs rm -rf
clean:
	@echo --- Invoking swift build --clean
	swift build --clean
build: clean fetch
	@echo --- Building package
	"$(BUILDCOMMAND)"
test: build
	@echo --- Running tests
	swift test
run: build
	@echo --- Starting server
	.build/debug/StockServiceApp ./Sources/<%= application_name %>App/config.json
