source 'https://rubygems.org'

gem "rake"
gem "cucumber", "~> 1.3.10"
gem "cucumber-rest-api", "= 0.3"
gem 'minke'
#gem 'minke-generator-swift' # Update this to the name of your gem
gem 'minke-generator-swift', :path => '/Users/nicj/Developer/gems/minke-generator-swift' # Update this to the name of your gem
